image: docker:19.03.13
variables:
  DOCKER_TLS_CERTDIR: ""
services:
  - docker:19.03.13-dind

stages:
  - publish

publish:
  except:
    - tags
  stage: publish
  script:
    - echo "version = '$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA';" >> version.js
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

release:
  only:
    - tags
  stage: publish
  script:
    - echo "version = '$CI_COMMIT_TAG';" >> version.js
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG
