image: registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image/master:stable
variables:
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:19.03.13-dind

stages:
  - publish

publish:
  stage: publish
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH
  
